DROP TABLE PASSENGER cascade constraints;
DROP TABLE AIRPLANE_TYPE cascade constraints;
DROP TABLE LUGGAGE cascade constraints;
DROP TABLE AIRPORT cascade constraints;
DROP TABLE EMPLOYEE cascade constraints;
DROP TABLE FLIGHT cascade constraints;
DROP TABLE TICKET cascade constraints;
DROP TABLE FLIGHT_ROUTE cascade constraints;


CREATE TABLE PASSENGER
(PASSENGER_ID VARCHAR(2),
LAST_NAME VARCHAR(15),
FIRST_NAME VARCHAR(15),
STREET VARCHAR(15),
CITY VARCHAR(15),
STATE CHAR(5),
POSTAL_CODE CHAR(5),
EMAIL VARCHAR(30),
COUNTRY CHAR(25),
    CONSTRAINT PASSENGER_PASSENGER_ID_PK PRIMARY KEY (PASSENGER_ID));

CREATE TABLE AIRPLANE_TYPE
(AIRPLANE_ID VARCHAR(6),
AIRPLANE_MODEL VARCHAR(5),
MAX_SEATS CHAR(3),
    CONSTRAINT AIRPLANE_TYPE_AIRPLANE_ID_PK PRIMARY KEY(AIRPLANE_ID));
   
CREATE TABLE LUGGAGE
(LUGGAGE_ID VARCHAR(3),
PASSENGER_ID VARCHAR(2),
WEIGHT VARCHAR(20),
PRICE VARCHAR(15),
     CONSTRAINT LUGGAGE_LUGGAGE_ID_PK PRIMARY KEY (LUGGAGE_ID),
     CONSTRAINT LUGGAGE_PASSENGER_ID_FK FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (PASSENGER_ID));

CREATE TABLE AIRPORT
(AIRPORT_ID CHAR(4),
CITY VARCHAR(30),
STATE VARCHAR(20),
AIRPORT_NAME CHAR(100),
    CONSTRAINT AIRPORT_AIRPORT_ID_PK PRIMARY KEY (AIRPORT_ID));

CREATE TABLE EMPLOYEE
(EMPLOYEE_ID CHAR(10),
LAST_NAME VARCHAR(15),
FIRST_NAME VARCHAR(15),
POSITION VARCHAR(15),
PHONE_NUMBER VARCHAR(15),
AIRPORT_ID CHAR(4),
    CONSTRAINT EMPLOYEE_EMPLOYEE_ID_PK PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT EMPLOYEE_AIRPORT_ID_FK FOREIGN KEY (AIRPORT_ID) REFERENCES AIRPORT (AIRPORT_ID));
    
CREATE TABLE FLIGHT
(FLIGHT_ID VARCHAR(5),
ARRIVAL_TIME CHAR(4),
DEPARTURE_TIME VARCHAR(4),
FLIGHT_DATE DATE,
AIRPLANE_ID VARCHAR(6),
    CONSTRAINT FLIGHT_AIRPLANE_ID_FK FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRPLANE_TYPE (AIRPLANE_ID),
    CONSTRAINT FLIGHT_FLIGHT_ID_PK PRIMARY KEY (FLIGHT_ID));

CREATE TABLE TICKET
(TICKET_ID VARCHAR(5),
PASSENGER_ID VARCHAR(4),
FLIGHT_ID VARCHAR(3),
SEAT_NUMBER CHAR(6),
    CONSTRAINT TICKET_PASSENGER_ID_FK FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (PASSENGER_ID),
    CONSTRAINT TICKET_FLIGHT_ID_FK FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT (FLIGHT_ID),
    CONSTRAINT TICKET_TICKET_ID_PK PRIMARY KEY (TICKET_ID));

CREATE TABLE FLIGHT_ROUTE
(ROUTE_ID CHAR(5),
FLIGHT_ID VARCHAR(3),
AIRLINE_COMPANY VARCHAR(6),
FLIGHT_TIME VARCHAR(10),
    CONSTRAINT FLIGHT_ROUTE_FLIGHT_ID_FK FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT (FLIGHT_ID),
    CONSTRAINT FLIGHT_ROUTE_ROUTE_ID_PK PRIMARY KEY (ROUTE_ID));
    
